-- Energyrite Database Setup Script
-- Run this in Supabase SQL Editor

-- 1. Create trigger functions first
CREATE OR REPLACE FUNCTION update_vehicle_settings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_fuel_gauge_settings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Create users table
CREATE TABLE IF NOT EXISTS public.users (
  id UUID NOT NULL,
  email TEXT NOT NULL,
  role TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  tech_admin BOOLEAN NULL DEFAULT FALSE,
  first_login BOOLEAN NULL DEFAULT TRUE,
  permissions JSONB NULL,
  energyrite BOOLEAN NULL,
  cost_code TEXT NULL,
  company TEXT NULL,
  site_id TEXT NULL,
  phone TEXT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE
);

-- 3. Create cost_centers table (legacy)
CREATE TABLE IF NOT EXISTS public.cost_centers (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  company TEXT NULL,
  cost_code TEXT NULL,
  CONSTRAINT cost_centers_pkey1 PRIMARY KEY (id)
);

-- 4. Create level_3_cost_centers table
CREATE TABLE IF NOT EXISTS public.level_3_cost_centers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cost_code TEXT NULL,
  company TEXT NULL,
  branch TEXT NULL,
  sub_branch TEXT NULL,
  cost_codes TEXT NULL,
  new_account_number TEXT NULL,
  parent_cost_code TEXT NULL,
  unique_id UUID NULL DEFAULT gen_random_uuid(),
  CONSTRAINT level_3_cost_centers_pkey PRIMARY KEY (id)
);

-- 5. Create level_4_cost_centers table
CREATE TABLE IF NOT EXISTS public.level_4_cost_centers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cost_code TEXT NULL,
  company TEXT NULL,
  branch TEXT NULL,
  sub_branch TEXT NULL,
  cost_codes TEXT NULL,
  new_account_number TEXT NULL,
  parent_cost_code TEXT NULL,
  unique_id UUID NULL DEFAULT gen_random_uuid(),
  CONSTRAINT level_4_cost_centers_pkey PRIMARY KEY (id)
);

-- 6. Create level_5_cost_centers table
CREATE TABLE IF NOT EXISTS public.level_5_cost_centers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cost_code TEXT NULL,
  company TEXT NULL,
  branch TEXT NULL,
  sub_branch TEXT NULL,
  cost_codes TEXT NULL,
  new_account_number TEXT NULL,
  parent_cost_code TEXT NULL,
  unique_id UUID NULL DEFAULT gen_random_uuid(),
  CONSTRAINT level_5_cost_centers_pkey PRIMARY KEY (id)
);

-- 7. Create vehicle_settings table
CREATE TABLE IF NOT EXISTS public.vehicle_settings (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  vehicle_id TEXT NOT NULL,
  tank_size NUMERIC(10, 2) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT vehicle_settings_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_settings_vehicle_id_key UNIQUE (vehicle_id)
);

CREATE INDEX IF NOT EXISTS idx_vehicle_settings_vehicle_id ON public.vehicle_settings USING btree (vehicle_id);

DROP TRIGGER IF EXISTS vehicle_settings_updated_at ON public.vehicle_settings;
CREATE TRIGGER vehicle_settings_updated_at 
BEFORE UPDATE ON public.vehicle_settings 
FOR EACH ROW 
EXECUTE FUNCTION update_vehicle_settings_updated_at();

-- 8. Create note_logs table
CREATE TABLE IF NOT EXISTS public.note_logs (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  vehicle_id TEXT NOT NULL,
  user_id UUID NOT NULL,
  user_email TEXT NULL,
  old_note TEXT NULL,
  new_note TEXT NULL,
  action TEXT NOT NULL,
  created_at TIMESTAMPTZ NULL DEFAULT NOW(),
  note_type TEXT NULL DEFAULT 'external',
  CONSTRAINT note_logs_pkey PRIMARY KEY (id),
  CONSTRAINT note_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
);

-- 9. Create fuel_gauge_settings table
CREATE TABLE IF NOT EXISTS public.fuel_gauge_settings (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  color_high TEXT NOT NULL DEFAULT '#00FF00',
  color_medium TEXT NOT NULL DEFAULT '#FFFF00',
  color_low TEXT NOT NULL DEFAULT '#FF0000',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fuel_gauge_settings_pkey PRIMARY KEY (id),
  CONSTRAINT fuel_gauge_settings_user_id_key UNIQUE (user_id),
  CONSTRAINT fuel_gauge_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_fuel_gauge_settings_user_id ON public.fuel_gauge_settings USING btree (user_id);

DROP TRIGGER IF EXISTS fuel_gauge_settings_updated_at ON public.fuel_gauge_settings;
CREATE TRIGGER fuel_gauge_settings_updated_at 
BEFORE UPDATE ON public.fuel_gauge_settings 
FOR EACH ROW 
EXECUTE FUNCTION update_fuel_gauge_settings_updated_at();

-- 10. Create energyrite_vehicle_lookup table (if needed)
CREATE TABLE IF NOT EXISTS public.energyrite_vehicle_lookup (
  plate TEXT NOT NULL,
  cost_code TEXT NULL,
  CONSTRAINT energyrite_vehicle_lookup_pkey PRIMARY KEY (plate)
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cost_centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.level_3_cost_centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.level_4_cost_centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.level_5_cost_centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.note_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fuel_gauge_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.energyrite_vehicle_lookup ENABLE ROW LEVEL SECURITY;

-- Create basic RLS policies (adjust as needed)
-- Allow authenticated users to read all tables
CREATE POLICY "Allow authenticated read" ON public.users FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.cost_centers FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.level_3_cost_centers FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.level_4_cost_centers FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.level_5_cost_centers FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.vehicle_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.note_logs FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.fuel_gauge_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.energyrite_vehicle_lookup FOR SELECT TO authenticated USING (true);

-- Allow users to manage their own settings
CREATE POLICY "Users can update own settings" ON public.fuel_gauge_settings FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own settings" ON public.fuel_gauge_settings FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Allow authenticated users to insert/update vehicle settings and notes
CREATE POLICY "Allow authenticated insert" ON public.vehicle_settings FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update" ON public.vehicle_settings FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert" ON public.note_logs FOR INSERT TO authenticated WITH CHECK (true);

-- Verification queries
SELECT 'Setup complete! Run these queries to verify:' AS status;
SELECT 'SELECT * FROM public.users;' AS query;
SELECT 'SELECT * FROM public.vehicle_settings;' AS query;
SELECT 'SELECT * FROM public.note_logs;' AS query;
SELECT 'SELECT * FROM public.fuel_gauge_settings;' AS query;
